"""adding cases model

Revision ID: 9f86e1db44e4
Revises: 
Create Date: 2020-08-16 15:06:42.253260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f86e1db44e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('cases', sa.Integer(), nullable=True),
    sa.Column('tests', sa.Integer(), nullable=True),
    sa.Column('positive', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_date'), 'cases', ['date'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_date'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
